---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/chmeliik/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-document-previewenv
